name: EasyShop
description: Grocerry APP in Flutter using TensorFlow Lite
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  collection: ^1.16.0
  image: ^3.2.2
  tflite_flutter: ^0.9.0
  tflite_flutter_helper:
    git:
      url: https://github.com/filofan1/tflite_flutter_helper.git
      ref: 783f15e5a87126159147d8ea30b98eea9207ac70
  flutter_barcode_scanner: ^2.0.0
  flutter_svg: ^1.1.6
  camera: ^0.8.1+3
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.2.3
  form_field_validator: ^1.1.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.1.6



dependency_overrides:
  ffi: ^1.0.0



dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true    
  assets:
    - assets/
    - assets/images/
    - assets/images/beverages_images/
    - assets/images/categories_images/
    - assets/images/grocery_images/
    - assets/icons/
    - assets/icons/account_icons/
    - assets/fonts/
    - assets/fonts/gilroy/


 
