// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVhdWRovivKOp6zFnJgAGbLFB4QIl_nJQ',
    appId: '1:554691725919:android:be92f18412612ff50869ea',
    messagingSenderId: '554691725919',
    projectId: 'esyshopping-e667d',
    storageBucket: 'esyshopping-e667d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL5wqm3Pd2Caf0PuStosot_Ch-agVVVPs',
    appId: '1:554691725919:ios:66583724420007ad0869ea',
    messagingSenderId: '554691725919',
    projectId: 'esyshopping-e667d',
    storageBucket: 'esyshopping-e667d.firebasestorage.app',
    androidClientId: '554691725919-nqb19ri4fk077h7cjkabhgfljeof5kvp.apps.googleusercontent.com',
    iosClientId: '554691725919-5nvb68jiivq1j0m8bk6vqt0b1f5v2vmb.apps.googleusercontent.com',
    iosBundleId: 'com.kodeco.plantreco',
  );

}